import { createContext, useContext, useState } from "react";

export const LANGUAGES = [
  { code: "en",  name: "English",   native: "English" },
  { code: "hi",  name: "Hindi",     native: "हिंदी" },
  { code: "ta",  name: "Tamil",     native: "தமிழ்" },
  { code: "te",  name: "Telugu",    native: "తెలుగు" },
  { code: "mr",  name: "Marathi",   native: "मराठी" },
  { code: "gu",  name: "Gujarati",  native: "ગુજરાતી" },
  { code: "kn",  name: "Kannada",   native: "ಕನ್ನಡ" },
  { code: "ml",  name: "Malayalam", native: "മലയാളം" },
  { code: "bn",  name: "Bengali",   native: "বাংলা" },
  { code: "pa",  name: "Punjabi",   native: "ਪੰਜਾਬੀ" },
];

const T = {
  en: {
    // Nav
    dashboard: "Dashboard", learn: "Learn", functions: "Functions",
    aiChat: "AI Chat", formulaAI: "Formula AI", excelAI: "Excel AI",
    pricing: "Pricing", signIn: "Sign in", signOut: "Sign out",
    upgrade: "Upgrade", getStarted: "Get Started", bookmarks: "Bookmarks",
    reviews: "Reviews", admin: "Admin", aiRespondingIn: "AI responds in",
    signedInAs: "Signed in as", free: "FREE", pro: "PRO",
    upgradeToProMenu: "Upgrade to Pro",
    // Login page
    pickUpTitle: "Pick up where you left off.",
    pickUpSubtitle: "Your saved chats, recent searches, and bookmarked tutorials are waiting.",
    signInToAccount: "Sign in to your account.",
    emailAddress: "Email address",
    password: "Password",
    forgotPassword: "Forgot password?",
    newHere: "New here?",
    createAccountLink: "Create an account",
    signingIn: "Signing in…",
    // Signup page
    createAccountTitle: "Master Excel — free.",
    createAccountOverline: "CREATE ACCOUNT",
    namePlaceholder: "Jane Doe",
    emailPlaceholder: "you@work.com",
    passwordPlaceholder: "At least 6 characters",
    createAccountBtn: "Create account",
    creating: "Creating…",
    alreadyHaveAccount: "Already have an account?",
    stopGooglingTitle: "Stop googling.",
    startMastering: "mastering",
    features: ["60+ Excel functions, indexed", "AI assistant powered by Groq", "Curated tutorials for real workflows"],
  },
  hi: {
    dashboard: "डैशबोर्ड", learn: "सीखें", functions: "फ़ंक्शन",
    aiChat: "AI चैट", formulaAI: "फ़ॉर्मूला AI", excelAI: "Excel AI",
    pricing: "मूल्य", signIn: "साइन इन", signOut: "साइन आउट",
    upgrade: "अपग्रेड", getStarted: "शुरू करें", bookmarks: "बुकमार्क",
    reviews: "समीक्षाएं", admin: "एडमिन", aiRespondingIn: "AI जवाब देगा",
    signedInAs: "लॉग इन:", free: "मुफ़्त", pro: "PRO",
    upgradeToProMenu: "Pro में अपग्रेड करें",
    pickUpTitle: "जहाँ छोड़ा था, वहीं से शुरू करें।",
    pickUpSubtitle: "आपकी सेव चैट, हाल की खोजें और बुकमार्क किए गए ट्यूटोरियल आपका इंतज़ार कर रहे हैं।",
    signInToAccount: "अपने खाते में साइन इन करें।",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड भूल गए?",
    newHere: "नए हैं?",
    createAccountLink: "खाता बनाएं",
    signingIn: "साइन इन हो रहा है…",
    createAccountTitle: "Excel मास्टर करें — मुफ़्त में।",
    createAccountOverline: "खाता बनाएं",
    namePlaceholder: "आपका नाम",
    emailPlaceholder: "आपका ईमेल",
    passwordPlaceholder: "कम से कम 6 अक्षर",
    createAccountBtn: "खाता बनाएं",
    creating: "बन रहा है…",
    alreadyHaveAccount: "पहले से खाता है?",
    stopGooglingTitle: "Google करना बंद करें।",
    startMastering: "महारत हासिल करें",
    features: ["60+ Excel फ़ंक्शन, इंडेक्स किए गए", "Groq द्वारा संचालित AI असिस्टेंट", "वास्तविक कार्यों के लिए चुने गए ट्यूटोरियल"],
  },
  ta: {
    dashboard: "டாஷ்போர்டு", learn: "கற்றுக்கொள்", functions: "செயல்பாடுகள்",
    aiChat: "AI அரட்டை", formulaAI: "சூத்திர AI", excelAI: "Excel AI",
    pricing: "விலை", signIn: "உள்நுழை", signOut: "வெளியேறு",
    upgrade: "மேம்படுத்து", getStarted: "தொடங்கு", bookmarks: "புக்மார்க்",
    reviews: "மதிப்புரைகள்", admin: "நிர்வாகம்", aiRespondingIn: "AI பதிலளிக்கிறது",
    signedInAs: "உள்நுழைந்தவர்:", free: "இலவசம்", pro: "PRO",
    upgradeToProMenu: "Pro-க்கு மேம்படுத்து",
    pickUpTitle: "நீங்கள் நிறுத்திய இடத்திலிருந்து தொடங்கவும்.",
    pickUpSubtitle: "உங்கள் சேமிக்கப்பட்ட அரட்டைகள், சமீபத்திய தேடல்கள் மற்றும் புக்மார்க் செய்யப்பட்ட பயிற்சிகள் காத்திருக்கின்றன.",
    signInToAccount: "உங்கள் கணக்கில் உள்நுழையவும்.",
    emailAddress: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    forgotPassword: "கடவுச்சொல் மறந்தீர்களா?",
    newHere: "புதியவரா?",
    createAccountLink: "கணக்கை உருவாக்குங்கள்",
    signingIn: "உள்நுழைகிறது…",
    createAccountTitle: "Excel கற்றுக்கொள்ளுங்கள் — இலவசமாக.",
    createAccountOverline: "கணக்கை உருவாக்கு",
    namePlaceholder: "உங்கள் பெயர்",
    emailPlaceholder: "உங்கள் மின்னஞ்சல்",
    passwordPlaceholder: "குறைந்தது 6 எழுத்துகள்",
    createAccountBtn: "கணக்கை உருவாக்கு",
    creating: "உருவாக்கப்படுகிறது…",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    stopGooglingTitle: "Google செய்வதை நிறுத்துங்கள்.",
    startMastering: "தேர்ச்சி பெறுங்கள்",
    features: ["60+ Excel செயல்பாடுகள்", "Groq மூலம் AI உதவியாளர்", "உண்மையான பணிகளுக்கான பயிற்சிகள்"],
  },
  te: {
    dashboard: "డాష్‌బోర్డ్", learn: "నేర్చుకో", functions: "ఫంక్షన్లు",
    aiChat: "AI చాట్", formulaAI: "ఫార్ములా AI", excelAI: "Excel AI",
    pricing: "ధర", signIn: "సైన్ ఇన్", signOut: "సైన్ అవుట్",
    upgrade: "అప్‌గ్రేడ్", getStarted: "ప్రారంభించు", bookmarks: "బుక్‌మార్క్లు",
    reviews: "సమీక్షలు", admin: "అడ్మిన్", aiRespondingIn: "AI జవాబిస్తుంది",
    signedInAs: "లాగిన్:", free: "ఉచితం", pro: "PRO",
    upgradeToProMenu: "Pro కి అప్‌గ్రేడ్",
    pickUpTitle: "మీరు ఆపిన చోటు నుండి కొనసాగించండి.",
    pickUpSubtitle: "మీ సేవ్ చేసిన చాట్‌లు, ఇటీవలి శోధనలు మరియు బుక్‌మార్క్ చేసిన ట్యుటోరియల్స్ వేచి ఉన్నాయి.",
    signInToAccount: "మీ ఖాతాలోకి సైన్ ఇన్ చేయండి.",
    emailAddress: "ఇమెయిల్ చిరునామా",
    password: "పాస్‌వర్డ్",
    forgotPassword: "పాస్‌వర్డ్ మర్చిపోయారా?",
    newHere: "కొత్తగా వచ్చారా?",
    createAccountLink: "ఖాతా సృష్టించండి",
    signingIn: "సైన్ ఇన్ అవుతోంది…",
    createAccountTitle: "Excel నేర్చుకోండి — ఉచితంగా.",
    createAccountOverline: "ఖాతా సృష్టించు",
    namePlaceholder: "మీ పేరు",
    emailPlaceholder: "మీ ఇమెయిల్",
    passwordPlaceholder: "కనీసం 6 అక్షరాలు",
    createAccountBtn: "ఖాతా సృష్టించు",
    creating: "సృష్టిస్తోంది…",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    stopGooglingTitle: "Google చేయడం ఆపండి.",
    startMastering: "నైపుణ్యం పొందండి",
    features: ["60+ Excel ఫంక్షన్లు", "Groq ద్వారా AI అసిస్టెంట్", "నిజమైన పనుల కోసం ట్యుటోరియల్స్"],
  },
  mr: {
    dashboard: "डॅशबोर्ड", learn: "शिका", functions: "फंक्शन",
    aiChat: "AI चॅट", formulaAI: "फॉर्म्युला AI", excelAI: "Excel AI",
    pricing: "किंमत", signIn: "साइन इन", signOut: "साइन आउट",
    upgrade: "अपग्रेड", getStarted: "सुरुवात करा", bookmarks: "बुकमार्क",
    reviews: "पुनरावलोकने", admin: "प्रशासक", aiRespondingIn: "AI उत्तर देतो",
    signedInAs: "लॉग इन:", free: "मोफत", pro: "PRO",
    upgradeToProMenu: "Pro मध्ये अपग्रेड करा",
    pickUpTitle: "जिथे सोडले होते तिथून सुरू करा.",
    pickUpSubtitle: "तुमच्या जतन केलेल्या चॅट्स, अलीकडील शोध आणि बुकमार्क केलेले ट्यूटोरियल्स वाट पाहत आहेत.",
    signInToAccount: "तुमच्या खात्यात साइन इन करा.",
    emailAddress: "ईमेल पत्ता",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड विसरलात?",
    newHere: "नवीन आहात?",
    createAccountLink: "खाते तयार करा",
    signingIn: "साइन इन होत आहे…",
    createAccountTitle: "Excel शिका — मोफत.",
    createAccountOverline: "खाते तयार करा",
    namePlaceholder: "तुमचे नाव",
    emailPlaceholder: "तुमचा ईमेल",
    passwordPlaceholder: "किमान 6 अक्षरे",
    createAccountBtn: "खाते तयार करा",
    creating: "तयार होत आहे…",
    alreadyHaveAccount: "आधीपासून खाते आहे?",
    stopGooglingTitle: "Google करणे थांबवा.",
    startMastering: "प्रावीण्य मिळवा",
    features: ["60+ Excel फंक्शन्स", "Groq द्वारे AI सहाय्यक", "वास्तविक कामांसाठी ट्यूटोरियल्स"],
  },
  gu: {
    dashboard: "ડેશબોર્ડ", learn: "શીખો", functions: "ફંક્શન",
    aiChat: "AI ચૅટ", formulaAI: "ફૉર્મ્યુલા AI", excelAI: "Excel AI",
    pricing: "કિંમત", signIn: "સાઇન ઇન", signOut: "સાઇન આઉટ",
    upgrade: "અપગ્રેડ", getStarted: "શરૂ કરો", bookmarks: "બુકમાર્ક",
    reviews: "સમીક્ષાઓ", admin: "એડમિન", aiRespondingIn: "AI જવાબ આપે છે",
    signedInAs: "લૉગ ઇન:", free: "મફત", pro: "PRO",
    upgradeToProMenu: "Pro માં અપગ્રેડ કરો",
    pickUpTitle: "જ્યાં છોડ્યું હતું ત્યાંથી ચાલુ કરો.",
    pickUpSubtitle: "તમારી સેવ કરેલ ચૅટ, તાજેતરની શોધ અને બુકમાર્ક કરેલ ટ્યૂટોરિયલ રાહ જોઈ રહ્યા છે.",
    signInToAccount: "તમારા ખાતામાં સાઇન ઇન કરો.",
    emailAddress: "ઇમેઇલ સરનામું",
    password: "પાસવર્ડ",
    forgotPassword: "પાસવર્ડ ભૂલ્યા?",
    newHere: "નવા છો?",
    createAccountLink: "ખાતું બનાવો",
    signingIn: "સાઇન ઇન થઈ રહ્યું છે…",
    createAccountTitle: "Excel શીખો — મફત.",
    createAccountOverline: "ખાતું બનાવો",
    namePlaceholder: "તમારું નામ",
    emailPlaceholder: "તમારો ઇમેઇલ",
    passwordPlaceholder: "ઓછામાં ઓછા 6 અક્ષરો",
    createAccountBtn: "ખાતું બનાવો",
    creating: "બની રહ્યું છે…",
    alreadyHaveAccount: "પહેલેથી ખાતું છે?",
    stopGooglingTitle: "Google કરવાનું બંધ કરો.",
    startMastering: "નિપુણ બનો",
    features: ["60+ Excel ફંક્શન્સ", "Groq દ્વારા AI સહાયક", "વાસ્તવિક કાર્ય માટે ટ્યૂટોરિયલ"],
  },
  kn: {
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", learn: "ಕಲಿಯಿರಿ", functions: "ಕಾರ್ಯಗಳು",
    aiChat: "AI ಚಾಟ್", formulaAI: "ಫಾರ್ಮುಲಾ AI", excelAI: "Excel AI",
    pricing: "ಬೆಲೆ", signIn: "ಸೈನ್ ಇನ್", signOut: "ಸೈನ್ ಔಟ್",
    upgrade: "ಅಪ್‌ಗ್ರೇಡ್", getStarted: "ಪ್ರಾರಂಭಿಸಿ", bookmarks: "ಬುಕ್‌ಮಾರ್ಕ್‌ಗಳು",
    reviews: "ವಿಮರ್ಶೆಗಳು", admin: "ಆಡ್ಮಿನ್", aiRespondingIn: "AI ಉತ್ತರಿಸುತ್ತದೆ",
    signedInAs: "ಲಾಗಿನ್:", free: "ಉಚಿತ", pro: "PRO",
    upgradeToProMenu: "Pro ಗೆ ಅಪ್‌ಗ್ರೇಡ್",
    pickUpTitle: "ನೀವು ನಿಲ್ಲಿಸಿದ ಕಡೆಯಿಂದ ಮುಂದುವರಿಸಿ.",
    pickUpSubtitle: "ನಿಮ್ಮ ಉಳಿಸಿದ ಚಾಟ್‌ಗಳು, ಇತ್ತೀಚಿನ ಹುಡುಕಾಟಗಳು ಮತ್ತು ಬುಕ್‌ಮಾರ್ಕ್ ಮಾಡಿದ ಟ್ಯುಟೋರಿಯಲ್‌ಗಳು ಕಾಯುತ್ತಿವೆ.",
    signInToAccount: "ನಿಮ್ಮ ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ.",
    emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    forgotPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?",
    newHere: "ಹೊಸಬರಾ?",
    createAccountLink: "ಖಾತೆ ತೆರೆಯಿರಿ",
    signingIn: "ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ…",
    createAccountTitle: "Excel ಕಲಿಯಿರಿ — ಉಚಿತವಾಗಿ.",
    createAccountOverline: "ಖಾತೆ ತೆರೆಯಿರಿ",
    namePlaceholder: "ನಿಮ್ಮ ಹೆಸರು",
    emailPlaceholder: "ನಿಮ್ಮ ಇಮೇಲ್",
    passwordPlaceholder: "ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳು",
    createAccountBtn: "ಖಾತೆ ತೆರೆಯಿರಿ",
    creating: "ರಚಿಸಲಾಗುತ್ತಿದೆ…",
    alreadyHaveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
    stopGooglingTitle: "Google ಮಾಡುವುದನ್ನು ನಿಲ್ಲಿಸಿ.",
    startMastering: "ಪ್ರಾವೀಣ್ಯ ಪಡೆಯಿರಿ",
    features: ["60+ Excel ಕಾರ್ಯಗಳು", "Groq ಮೂಲಕ AI ಸಹಾಯಕ", "ನೈಜ ಕೆಲಸಗಳಿಗಾಗಿ ಟ್ಯುಟೋರಿಯಲ್‌ಗಳು"],
  },
  ml: {
    dashboard: "ഡാഷ്‌ബോർഡ്", learn: "പഠിക്കൂ", functions: "ഫങ്ഷനുകൾ",
    aiChat: "AI ചാറ്റ്", formulaAI: "ഫോർമുല AI", excelAI: "Excel AI",
    pricing: "വില", signIn: "സൈൻ ഇൻ", signOut: "സൈൻ ഔട്ട്",
    upgrade: "അപ്‌ഗ്രേഡ്", getStarted: "ആരംഭിക്കൂ", bookmarks: "ബുക്ക്‌മാർക്കുകൾ",
    reviews: "അവലോകനങ്ങൾ", admin: "അഡ്‌മിൻ", aiRespondingIn: "AI മറുപടി നൽകുന്നു",
    signedInAs: "ലോഗിൻ:", free: "സൗജന്യം", pro: "PRO",
    upgradeToProMenu: "Pro-ലേക്ക് അപ്‌ഗ്രേഡ്",
    pickUpTitle: "നിർത്തിയ ഇടത്ത് നിന്ന് തുടരൂ.",
    pickUpSubtitle: "നിങ്ങളുടെ സേവ് ചെയ്ത ചാറ്റുകൾ, സമീപകാല തിരയലുകൾ, ബുക്ക്‌മാർക്ക് ചെയ്ത ട്യൂട്ടോറിയലുകൾ കാത്തിരിക്കുന്നു.",
    signInToAccount: "നിങ്ങളുടെ അക്കൗണ്ടിൽ സൈൻ ഇൻ ചെയ്യൂ.",
    emailAddress: "ഇമെയിൽ വിലാസം",
    password: "പാസ്‌വേഡ്",
    forgotPassword: "പാസ്‌വേഡ് മറന്നോ?",
    newHere: "പുതിയ ഉപയോക്താവോ?",
    createAccountLink: "അക്കൗണ്ട് ഉണ്ടാക്കൂ",
    signingIn: "സൈൻ ഇൻ ആകുന്നു…",
    createAccountTitle: "Excel പഠിക്കൂ — സൗജന്യമായി.",
    createAccountOverline: "അക്കൗണ്ട് ഉണ്ടാക്കൂ",
    namePlaceholder: "നിങ്ങളുടെ പേര്",
    emailPlaceholder: "നിങ്ങളുടെ ഇമെയിൽ",
    passwordPlaceholder: "കുറഞ്ഞത് 6 അക്ഷരങ്ങൾ",
    createAccountBtn: "അക്കൗണ്ട് ഉണ്ടാക്കൂ",
    creating: "ഉണ്ടാക്കുന്നു…",
    alreadyHaveAccount: "ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?",
    stopGooglingTitle: "Google ചെയ്യുന്നത് നിർത്തൂ.",
    startMastering: "വൈദഗ്ദ്ധ്യം നേടൂ",
    features: ["60+ Excel ഫങ്ഷനുകൾ", "Groq ഉപയോഗിച്ച് AI അസിസ്റ്റന്റ്", "യഥാർഥ ജോലിക്കായി ട്യൂട്ടോറിയലുകൾ"],
  },
  bn: {
    dashboard: "ড্যাশবোর্ড", learn: "শিখুন", functions: "ফাংশন",
    aiChat: "AI চ্যাট", formulaAI: "ফর্মুলা AI", excelAI: "Excel AI",
    pricing: "মূল্য", signIn: "সাইন ইন", signOut: "সাইন আউট",
    upgrade: "আপগ্রেড", getStarted: "শুরু করুন", bookmarks: "বুকমার্ক",
    reviews: "পর্যালোচনা", admin: "অ্যাডমিন", aiRespondingIn: "AI উত্তর দেয়",
    signedInAs: "লগইন:", free: "বিনামূল্যে", pro: "PRO",
    upgradeToProMenu: "Pro-তে আপগ্রেড করুন",
    pickUpTitle: "যেখানে ছেড়েছিলেন সেখান থেকে শুরু করুন।",
    pickUpSubtitle: "আপনার সেভ করা চ্যাট, সাম্প্রতিক অনুসন্ধান এবং বুকমার্ক করা টিউটোরিয়াল অপেক্ষা করছে।",
    signInToAccount: "আপনার অ্যাকাউন্টে সাইন ইন করুন।",
    emailAddress: "ইমেইল ঠিকানা",
    password: "পাসওয়ার্ড",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    newHere: "নতুন এখানে?",
    createAccountLink: "অ্যাকাউন্ট তৈরি করুন",
    signingIn: "সাইন ইন হচ্ছে…",
    createAccountTitle: "Excel শিখুন — বিনামূল্যে।",
    createAccountOverline: "অ্যাকাউন্ট তৈরি করুন",
    namePlaceholder: "আপনার নাম",
    emailPlaceholder: "আপনার ইমেইল",
    passwordPlaceholder: "কমপক্ষে ৬ অক্ষর",
    createAccountBtn: "অ্যাকাউন্ট তৈরি করুন",
    creating: "তৈরি হচ্ছে…",
    alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    stopGooglingTitle: "Google করা বন্ধ করুন।",
    startMastering: "দক্ষতা অর্জন করুন",
    features: ["60+ Excel ফাংশন", "Groq দ্বারা AI সহায়তা", "বাস্তব কাজের জন্য টিউটোরিয়াল"],
  },
  pa: {
    dashboard: "ਡੈਸ਼ਬੋਰਡ", learn: "ਸਿੱਖੋ", functions: "ਫੰਕਸ਼ਨ",
    aiChat: "AI ਚੈਟ", formulaAI: "ਫਾਰਮੂਲਾ AI", excelAI: "Excel AI",
    pricing: "ਕੀਮਤ", signIn: "ਸਾਈਨ ਇਨ", signOut: "ਸਾਈਨ ਆਊਟ",
    upgrade: "ਅੱਪਗ੍ਰੇਡ", getStarted: "ਸ਼ੁਰੂ ਕਰੋ", bookmarks: "ਬੁੱਕਮਾਰਕ",
    reviews: "ਸਮੀਖਿਆਵਾਂ", admin: "ਐਡਮਿਨ", aiRespondingIn: "AI ਜਵਾਬ ਦਿੰਦਾ ਹੈ",
    signedInAs: "ਲੌਗਇਨ:", free: "ਮੁਫ਼ਤ", pro: "PRO",
    upgradeToProMenu: "Pro ਵਿੱਚ ਅੱਪਗ੍ਰੇਡ ਕਰੋ",
    pickUpTitle: "ਜਿੱਥੇ ਛੱਡਿਆ ਸੀ ਉੱਥੋਂ ਸ਼ੁਰੂ ਕਰੋ।",
    pickUpSubtitle: "ਤੁਹਾਡੀਆਂ ਸੇਵ ਕੀਤੀਆਂ ਚੈਟਾਂ, ਹਾਲੀਆ ਖੋਜਾਂ ਅਤੇ ਬੁੱਕਮਾਰਕ ਕੀਤੇ ਟਿਊਟੋਰੀਅਲ ਉਡੀਕ ਕਰ ਰਹੇ ਹਨ।",
    signInToAccount: "ਆਪਣੇ ਖਾਤੇ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ।",
    emailAddress: "ਈਮੇਲ ਪਤਾ",
    password: "ਪਾਸਵਰਡ",
    forgotPassword: "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?",
    newHere: "ਨਵੇਂ ਹੋ?",
    createAccountLink: "ਖਾਤਾ ਬਣਾਓ",
    signingIn: "ਸਾਈਨ ਇਨ ਹੋ ਰਿਹਾ ਹੈ…",
    createAccountTitle: "Excel ਸਿੱਖੋ — ਮੁਫ਼ਤ ਵਿੱਚ।",
    createAccountOverline: "ਖਾਤਾ ਬਣਾਓ",
    namePlaceholder: "ਤੁਹਾਡਾ ਨਾਮ",
    emailPlaceholder: "ਤੁਹਾਡੀ ਈਮੇਲ",
    passwordPlaceholder: "ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰ",
    createAccountBtn: "ਖਾਤਾ ਬਣਾਓ",
    creating: "ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ…",
    alreadyHaveAccount: "ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?",
    stopGooglingTitle: "Google ਕਰਨਾ ਬੰਦ ਕਰੋ।",
    startMastering: "ਮੁਹਾਰਤ ਹਾਸਲ ਕਰੋ",
    features: ["60+ Excel ਫੰਕਸ਼ਨ", "Groq ਦੁਆਰਾ AI ਸਹਾਇਕ", "ਅਸਲ ਕੰਮਾਂ ਲਈ ਟਿਊਟੋਰੀਅਲ"],
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(
    () => localStorage.getItem("xlsbuddy_lang") || "en"
  );

  const setLanguage = (code) => {
    localStorage.setItem("xlsbuddy_lang", code);
    setLanguageState(code);
  };

  const current = LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];
  const t = (key) => T[language]?.[key] ?? T.en[key] ?? key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, current, LANGUAGES, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
