import { createContext, useContext, useState } from "react";

export const LANGUAGES = [
  { code: "en",  name: "English",   native: "English" },
  { code: "hi",  name: "Hindi",     native: "हिंदी" },
  { code: "ta",  name: "Tamil",     native: "தமிழ்" },
  { code: "te",  name: "Telugu",    native: "తెలుగు" },
  { code: "mr",  name: "Marathi",   native: "मराठी" },
  { code: "gu",  name: "Gujarati",  native: "ગુજરાતી" },
  { code: "kn",  name: "Kannada",   native: "ಕನ್ನಡ" },
  { code: "ml",  name: "Malayalam", native: "മലയാളം" },
  { code: "bn",  name: "Bengali",   native: "বাংলা" },
  { code: "pa",  name: "Punjabi",   native: "ਪੰਜਾਬੀ" },
];

const T = {
  en: {
    // Nav
    dashboard: "Dashboard", learn: "Learn", functions: "Functions",
    aiChat: "AI Chat", formulaAI: "Formula AI", excelAI: "Excel AI",
    pricing: "Pricing", signIn: "Sign in", signOut: "Sign out",
    upgrade: "Upgrade", getStarted: "Get Started", bookmarks: "Bookmarks",
    reviews: "Reviews", admin: "Admin", aiRespondingIn: "AI responds in",
    signedInAs: "Signed in as", free: "FREE", pro: "PRO",
    upgradeToProMenu: "Upgrade to Pro",
    // Login page
    pickUpTitle: "Pick up where you left off.",
    pickUpSubtitle: "Your saved chats, recent searches, and bookmarked tutorials are waiting.",
    signInToAccount: "Sign in to your account.",
    emailAddress: "Email address",
    password: "Password",
    forgotPassword: "Forgot password?",
    newHere: "New here?",
    createAccountLink: "Create an account",
    signingIn: "Signing in…",
    // Signup page
    createAccountTitle: "Master Excel — free.",
    createAccountOverline: "CREATE ACCOUNT",
    namePlaceholder: "Jane Doe",
    emailPlaceholder: "you@work.com",
    passwordPlaceholder: "At least 6 characters",
    createAccountBtn: "Create account",
    creating: "Creating…",
    alreadyHaveAccount: "Already have an account?",
    stopGooglingTitle: "Stop googling.",
    startMastering: "mastering",
    features: ["60+ Excel functions, indexed", "AI assistant powered by Groq", "Curated tutorials for real workflows"],
    // Dashboard
    dashboardLabel: "XLSBUDDY DASHBOARD",
    welcomeBack: "Welcome back",
    dashHeroSub: "Search Excel formulas, learn tutorials, and get AI-powered help in seconds.",
    browseFunctions: "Browse Functions",
    askAI: "Ask AI",
    tutorials: "Tutorials",
    statFunctions: "FUNCTIONS", statTutorials: "TUTORIALS", statAssistant: "ASSISTANT", statSupport: "SUPPORT",
    toolsLabel: "TOOLS", toolsHeading: "Everything you need.",
    tileFnTitle: "Functions Library", tileFnDesc: "Browse 60+ Excel functions by category. Syntax, examples, and real use cases.",
    tileAiTitle: "AI Assistant", tileAiDesc: "Ask anything about Excel — formulas, errors, best practices — and get instant answers.",
    tileTutTitle: "Tutorials", tileTutDesc: "Curated guides for pivots, lookups, conditional formatting, errors, and more.",
    tileBmTitle: "Bookmarks", tileBmDesc: "Quick access to functions and tutorials you've saved.",
    tileFgTitle: "Formula Generator", tileFgDesc: "Describe what you want in plain English — get the exact Excel formula instantly.",
    tileQsTitle: "Quick Search", tileQsDesc: "Find any function in less than a second by name or use case.",
    proTipLabel: "Pro Tip",
    proTipTitle: "Unlock unlimited AI chat + advanced tutorials",
    proTipDesc: "Upgrade to XLSBuddy Pro and get unlimited formula help, priority AI responses, and exclusive advanced Excel content.",
    upgradeToPro: "Upgrade to Pro", shareApp: "Share App",
  },
  hi: {
    dashboard: "डैशबोर्ड", learn: "सीखें", functions: "फ़ंक्शन",
    aiChat: "AI चैट", formulaAI: "फ़ॉर्मूला AI", excelAI: "Excel AI",
    pricing: "मूल्य", signIn: "साइन इन", signOut: "साइन आउट",
    upgrade: "अपग्रेड", getStarted: "शुरू करें", bookmarks: "बुकमार्क",
    reviews: "समीक्षाएं", admin: "एडमिन", aiRespondingIn: "AI जवाब देगा",
    signedInAs: "लॉग इन:", free: "मुफ़्त", pro: "PRO",
    upgradeToProMenu: "Pro में अपग्रेड करें",
    pickUpTitle: "जहाँ छोड़ा था, वहीं से शुरू करें।",
    pickUpSubtitle: "आपकी सेव चैट, हाल की खोजें और बुकमार्क किए गए ट्यूटोरियल आपका इंतज़ार कर रहे हैं।",
    signInToAccount: "अपने खाते में साइन इन करें।",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड भूल गए?",
    newHere: "नए हैं?",
    createAccountLink: "खाता बनाएं",
    signingIn: "साइन इन हो रहा है…",
    createAccountTitle: "Excel मास्टर करें — मुफ़्त में।",
    createAccountOverline: "खाता बनाएं",
    namePlaceholder: "आपका नाम",
    emailPlaceholder: "आपका ईमेल",
    passwordPlaceholder: "कम से कम 6 अक्षर",
    createAccountBtn: "खाता बनाएं",
    creating: "बन रहा है…",
    alreadyHaveAccount: "पहले से खाता है?",
    stopGooglingTitle: "Google करना बंद करें।",
    startMastering: "महारत हासिल करें",
    features: ["60+ Excel फ़ंक्शन, इंडेक्स किए गए", "Groq द्वारा संचालित AI असिस्टेंट", "वास्तविक कार्यों के लिए चुने गए ट्यूटोरियल"],
    dashboardLabel: "XLSBUDDY डैशबोर्ड", welcomeBack: "वापस स्वागत है",
    dashHeroSub: "Excel फ़ॉर्मूले खोजें, ट्यूटोरियल सीखें, और सेकंड में AI मदद पाएं।",
    browseFunctions: "फ़ंक्शन देखें", askAI: "AI से पूछें", tutorials: "ट्यूटोरियल",
    statFunctions: "फ़ंक्शन", statTutorials: "ट्यूटोरियल", statAssistant: "सहायक", statSupport: "सहायता",
    toolsLabel: "टूल्स", toolsHeading: "सब कुछ जो आपको चाहिए।",
    tileFnTitle: "फ़ंक्शन लाइब्रेरी", tileFnDesc: "60+ Excel फ़ंक्शन ब्राउज़ करें। सिंटैक्स, उदाहरण और उपयोग।",
    tileAiTitle: "AI सहायक", tileAiDesc: "Excel के बारे में कुछ भी पूछें — फ़ॉर्मूला, एरर — तुरंत जवाब पाएं।",
    tileTutTitle: "ट्यूटोरियल", tileTutDesc: "पिवट, लुकअप, कंडिशनल फ़ॉर्मैटिंग के लिए गाइड।",
    tileBmTitle: "बुकमार्क", tileBmDesc: "सेव किए गए फ़ंक्शन और ट्यूटोरियल तक त्वरित पहुंच।",
    tileFgTitle: "फ़ॉर्मूला जेनरेटर", tileFgDesc: "सरल भाषा में बताएं — सटीक Excel फ़ॉर्मूला पाएं।",
    tileQsTitle: "त्वरित खोज", tileQsDesc: "नाम या उपयोग से कोई भी फ़ंक्शन एक सेकंड में खोजें।",
    proTipLabel: "Pro टिप", proTipTitle: "असीमित AI चैट + एडवांस ट्यूटोरियल अनलॉक करें",
    proTipDesc: "XLSBuddy Pro में अपग्रेड करें और असीमित फ़ॉर्मूला मदद, प्राथमिकता AI, एक्सक्लूसिव कंटेंट पाएं।",
    upgradeToPro: "Pro में अपग्रेड करें", shareApp: "ऐप शेयर करें",
  },
  ta: {
    dashboard: "டாஷ்போர்டு", learn: "கற்றுக்கொள்", functions: "செயல்பாடுகள்",
    aiChat: "AI அரட்டை", formulaAI: "சூத்திர AI", excelAI: "Excel AI",
    pricing: "விலை", signIn: "உள்நுழை", signOut: "வெளியேறு",
    upgrade: "மேம்படுத்து", getStarted: "தொடங்கு", bookmarks: "புக்மார்க்",
    reviews: "மதிப்புரைகள்", admin: "நிர்வாகம்", aiRespondingIn: "AI பதிலளிக்கிறது",
    signedInAs: "உள்நுழைந்தவர்:", free: "இலவசம்", pro: "PRO",
    upgradeToProMenu: "Pro-க்கு மேம்படுத்து",
    pickUpTitle: "நீங்கள் நிறுத்திய இடத்திலிருந்து தொடங்கவும்.",
    pickUpSubtitle: "உங்கள் சேமிக்கப்பட்ட அரட்டைகள், சமீபத்திய தேடல்கள் மற்றும் புக்மார்க் செய்யப்பட்ட பயிற்சிகள் காத்திருக்கின்றன.",
    signInToAccount: "உங்கள் கணக்கில் உள்நுழையவும்.",
    emailAddress: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    forgotPassword: "கடவுச்சொல் மறந்தீர்களா?",
    newHere: "புதியவரா?",
    createAccountLink: "கணக்கை உருவாக்குங்கள்",
    signingIn: "உள்நுழைகிறது…",
    createAccountTitle: "Excel கற்றுக்கொள்ளுங்கள் — இலவசமாக.",
    createAccountOverline: "கணக்கை உருவாக்கு",
    namePlaceholder: "உங்கள் பெயர்",
    emailPlaceholder: "உங்கள் மின்னஞ்சல்",
    passwordPlaceholder: "குறைந்தது 6 எழுத்துகள்",
    createAccountBtn: "கணக்கை உருவாக்கு",
    creating: "உருவாக்கப்படுகிறது…",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    stopGooglingTitle: "Google செய்வதை நிறுத்துங்கள்.",
    startMastering: "தேர்ச்சி பெறுங்கள்",
    features: ["60+ Excel செயல்பாடுகள்", "Groq மூலம் AI உதவியாளர்", "உண்மையான பணிகளுக்கான பயிற்சிகள்"],
    dashboardLabel: "XLSBUDDY டாஷ்போர்டு", welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    dashHeroSub: "Excel சூத்திரங்களை தேடுங்கள், பயிற்சிகள் கற்கலாம், AI உதவி பெறுங்கள்.",
    browseFunctions: "செயல்பாடுகள் பார்க்க", askAI: "AI கேள்", tutorials: "பயிற்சிகள்",
    statFunctions: "செயல்பாடுகள்", statTutorials: "பயிற்சிகள்", statAssistant: "உதவியாளர்", statSupport: "ஆதரவு",
    toolsLabel: "கருவிகள்", toolsHeading: "உங்களுக்கு தேவையான அனைத்தும்.",
    tileFnTitle: "செயல்பாட்டு நூலகம்", tileFnDesc: "60+ Excel செயல்பாடுகளை வகைப்படி தேடுங்கள்.",
    tileAiTitle: "AI உதவியாளர்", tileAiDesc: "Excel பற்றி எதையும் கேளுங்கள் — உடனடி பதில் பெறுங்கள்.",
    tileTutTitle: "பயிற்சிகள்", tileTutDesc: "பிவோட், லுக்அப், கண்டிஷனல் ஃபார்மாட்டிங் வழிகாட்டிகள்.",
    tileBmTitle: "புக்மார்க்", tileBmDesc: "சேமித்த செயல்பாடுகள் மற்றும் பயிற்சிகளை விரைவாக அணுகுங்கள்.",
    tileFgTitle: "சூத்திர உருவாக்கி", tileFgDesc: "தமிழில் சொல்லுங்கள் — சரியான Excel சூத்திரம் பெறுங்கள்.",
    tileQsTitle: "விரைவு தேடல்", tileQsDesc: "எந்த செயல்பாட்டையும் ஒரு நொடியில் தேடுங்கள்.",
    proTipLabel: "Pro குறிப்பு", proTipTitle: "வரம்பற்ற AI சேவை + மேம்பட்ட பயிற்சிகள்",
    proTipDesc: "XLSBuddy Pro-க்கு மேம்படுத்தி வரம்பற்ற உதவி பெறுங்கள்.",
    upgradeToPro: "Pro-க்கு மேம்படுத்து", shareApp: "பகிர்",
  },
  te: {
    dashboard: "డాష్‌బోర్డ్", learn: "నేర్చుకో", functions: "ఫంక్షన్లు",
    aiChat: "AI చాట్", formulaAI: "ఫార్ములా AI", excelAI: "Excel AI",
    pricing: "ధర", signIn: "సైన్ ఇన్", signOut: "సైన్ అవుట్",
    upgrade: "అప్‌గ్రేడ్", getStarted: "ప్రారంభించు", bookmarks: "బుక్‌మార్క్లు",
    reviews: "సమీక్షలు", admin: "అడ్మిన్", aiRespondingIn: "AI జవాబిస్తుంది",
    signedInAs: "లాగిన్:", free: "ఉచితం", pro: "PRO",
    upgradeToProMenu: "Pro కి అప్‌గ్రేడ్",
    pickUpTitle: "మీరు ఆపిన చోటు నుండి కొనసాగించండి.",
    pickUpSubtitle: "మీ సేవ్ చేసిన చాట్‌లు, ఇటీవలి శోధనలు మరియు బుక్‌మార్క్ చేసిన ట్యుటోరియల్స్ వేచి ఉన్నాయి.",
    signInToAccount: "మీ ఖాతాలోకి సైన్ ఇన్ చేయండి.",
    emailAddress: "ఇమెయిల్ చిరునామా",
    password: "పాస్‌వర్డ్",
    forgotPassword: "పాస్‌వర్డ్ మర్చిపోయారా?",
    newHere: "కొత్తగా వచ్చారా?",
    createAccountLink: "ఖాతా సృష్టించండి",
    signingIn: "సైన్ ఇన్ అవుతోంది…",
    createAccountTitle: "Excel నేర్చుకోండి — ఉచితంగా.",
    createAccountOverline: "ఖాతా సృష్టించు",
    namePlaceholder: "మీ పేరు",
    emailPlaceholder: "మీ ఇమెయిల్",
    passwordPlaceholder: "కనీసం 6 అక్షరాలు",
    createAccountBtn: "ఖాతా సృష్టించు",
    creating: "సృష్టిస్తోంది…",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    stopGooglingTitle: "Google చేయడం ఆపండి.",
    startMastering: "నైపుణ్యం పొందండి",
    features: ["60+ Excel ఫంక్షన్లు", "Groq ద్వారా AI అసిస్టెంట్", "నిజమైన పనుల కోసం ట్యుటోరియల్స్"],
    dashboardLabel: "XLSBUDDY డాష్‌బోర్డ్", welcomeBack: "తిరిగి స్వాగతం",
    dashHeroSub: "Excel ఫార్ములాలు వెతకండి, ట్యుటోరియల్స్ నేర్చుకోండి, AI సహాయం పొందండి.",
    browseFunctions: "ఫంక్షన్లు చూడండి", askAI: "AI అడగండి", tutorials: "ట్యుటోరియల్స్",
    statFunctions: "ఫంక్షన్లు", statTutorials: "ట్యుటోరియల్స్", statAssistant: "సహాయకుడు", statSupport: "మద్దతు",
    toolsLabel: "సాధనాలు", toolsHeading: "మీకు కావలసినదంతా.",
    tileFnTitle: "ఫంక్షన్స్ లైబ్రరీ", tileFnDesc: "60+ Excel ఫంక్షన్లు వర్గాల వారీగా చూడండి.",
    tileAiTitle: "AI సహాయకుడు", tileAiDesc: "Excel గురించి ఏదైనా అడగండి — వెంటనే జవాబు పొందండి.",
    tileTutTitle: "ట్యుటోరియల్స్", tileTutDesc: "పివట్, లుక్అప్, కండిషనల్ ఫార్మాటింగ్ గైడ్లు.",
    tileBmTitle: "బుక్‌మార్క్లు", tileBmDesc: "సేవ్ చేసిన ఫంక్షన్లు మరియు ట్యుటోరియల్స్ వేగంగా యాక్సెస్.",
    tileFgTitle: "ఫార్ములా జెనరేటర్", tileFgDesc: "సరళంగా చెప్పండి — సరైన Excel ఫార్ములా పొందండి.",
    tileQsTitle: "త్వరిత వెతుకు", tileQsDesc: "ఏ ఫంక్షన్నైనా ఒక సెకండులో వెతకండి.",
    proTipLabel: "Pro చిట్కా", proTipTitle: "అపరిమిత AI చాట్ + అడ్వాన్స్డ్ ట్యుటోరియల్స్",
    proTipDesc: "XLSBuddy Pro కి అప్‌గ్రేడ్ చేసి అపరిమిత సహాయం పొందండి.",
    upgradeToPro: "Pro కి అప్‌గ్రేడ్", shareApp: "యాప్ షేర్",
  },
  mr: {
    dashboard: "डॅशबोर्ड", learn: "शिका", functions: "फंक्शन",
    aiChat: "AI चॅट", formulaAI: "फॉर्म्युला AI", excelAI: "Excel AI",
    pricing: "किंमत", signIn: "साइन इन", signOut: "साइन आउट",
    upgrade: "अपग्रेड", getStarted: "सुरुवात करा", bookmarks: "बुकमार्क",
    reviews: "पुनरावलोकने", admin: "प्रशासक", aiRespondingIn: "AI उत्तर देतो",
    signedInAs: "लॉग इन:", free: "मोफत", pro: "PRO",
    upgradeToProMenu: "Pro मध्ये अपग्रेड करा",
    pickUpTitle: "जिथे सोडले होते तिथून सुरू करा.",
    pickUpSubtitle: "तुमच्या जतन केलेल्या चॅट्स, अलीकडील शोध आणि बुकमार्क केलेले ट्यूटोरियल्स वाट पाहत आहेत.",
    signInToAccount: "तुमच्या खात्यात साइन इन करा.",
    emailAddress: "ईमेल पत्ता",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड विसरलात?",
    newHere: "नवीन आहात?",
    createAccountLink: "खाते तयार करा",
    signingIn: "साइन इन होत आहे…",
    createAccountTitle: "Excel शिका — मोफत.",
    createAccountOverline: "खाते तयार करा",
    namePlaceholder: "तुमचे नाव",
    emailPlaceholder: "तुमचा ईमेल",
    passwordPlaceholder: "किमान 6 अक्षरे",
    createAccountBtn: "खाते तयार करा",
    creating: "तयार होत आहे…",
    alreadyHaveAccount: "आधीपासून खाते आहे?",
    stopGooglingTitle: "Google करणे थांबवा.",
    startMastering: "प्रावीण्य मिळवा",
    features: ["60+ Excel फंक्शन्स", "Groq द्वारे AI सहाय्यक", "वास्तविक कामांसाठी ट्यूटोरियल्स"],
    dashboardLabel: "XLSBUDDY डॅशबोर्ड", welcomeBack: "परत स्वागत आहे",
    dashHeroSub: "Excel फॉर्म्युले शोधा, ट्यूटोरियल शिका आणि AI मदत मिळवा.",
    browseFunctions: "फंक्शन पहा", askAI: "AI विचारा", tutorials: "ट्यूटोरियल",
    statFunctions: "फंक्शन्स", statTutorials: "ट्यूटोरियल्स", statAssistant: "सहाय्यक", statSupport: "मदत",
    toolsLabel: "साधने", toolsHeading: "तुम्हाला जे हवे ते सगळे.",
    tileFnTitle: "फंक्शन लायब्ररी", tileFnDesc: "60+ Excel फंक्शन्स श्रेणीनुसार पहा.",
    tileAiTitle: "AI सहाय्यक", tileAiDesc: "Excel बद्दल काहीही विचारा — तात्काळ उत्तर मिळवा.",
    tileTutTitle: "ट्यूटोरियल", tileTutDesc: "पिव्होट, लुकअप, कंडिशनल फॉरमॅटिंगसाठी गाइड.",
    tileBmTitle: "बुकमार्क", tileBmDesc: "सेव्ह केलेल्या फंक्शन्स आणि ट्यूटोरियलमध्ये त्वरित प्रवेश.",
    tileFgTitle: "फॉर्म्युला जनरेटर", tileFgDesc: "सोप्या भाषेत सांगा — अचूक Excel फॉर्म्युला मिळवा.",
    tileQsTitle: "जलद शोध", tileQsDesc: "कोणतेही फंक्शन एका सेकंदात शोधा.",
    proTipLabel: "Pro टिप", proTipTitle: "अमर्यादित AI चॅट + प्रगत ट्यूटोरियल अनलॉक करा",
    proTipDesc: "XLSBuddy Pro मध्ये अपग्रेड करा आणि अमर्यादित मदत मिळवा.",
    upgradeToPro: "Pro मध्ये अपग्रेड करा", shareApp: "ॲप शेअर करा",
  },
  gu: {
    dashboard: "ડેશબોર્ડ", learn: "શીખો", functions: "ફંક્શન",
    aiChat: "AI ચૅટ", formulaAI: "ફૉર્મ્યુલા AI", excelAI: "Excel AI",
    pricing: "કિંમત", signIn: "સાઇન ઇન", signOut: "સાઇન આઉટ",
    upgrade: "અપગ્રેડ", getStarted: "શરૂ કરો", bookmarks: "બુકમાર્ક",
    reviews: "સમીક્ષાઓ", admin: "એડમિન", aiRespondingIn: "AI જવાબ આપે છે",
    signedInAs: "લૉગ ઇન:", free: "મફત", pro: "PRO",
    upgradeToProMenu: "Pro માં અપગ્રેડ કરો",
    pickUpTitle: "જ્યાં છોડ્યું હતું ત્યાંથી ચાલુ કરો.",
    pickUpSubtitle: "તમારી સેવ કરેલ ચૅટ, તાજેતરની શોધ અને બુકમાર્ક કરેલ ટ્યૂટોરિયલ રાહ જોઈ રહ્યા છે.",
    signInToAccount: "તમારા ખાતામાં સાઇન ઇન કરો.",
    emailAddress: "ઇમેઇલ સરનામું",
    password: "પાસવર્ડ",
    forgotPassword: "પાસવર્ડ ભૂલ્યા?",
    newHere: "નવા છો?",
    createAccountLink: "ખાતું બનાવો",
    signingIn: "સાઇન ઇન થઈ રહ્યું છે…",
    createAccountTitle: "Excel શીખો — મફત.",
    createAccountOverline: "ખાતું બનાવો",
    namePlaceholder: "તમારું નામ",
    emailPlaceholder: "તમારો ઇમેઇલ",
    passwordPlaceholder: "ઓછામાં ઓછા 6 અક્ષરો",
    createAccountBtn: "ખાતું બનાવો",
    creating: "બની રહ્યું છે…",
    alreadyHaveAccount: "પહેલેથી ખાતું છે?",
    stopGooglingTitle: "Google કરવાનું બંધ કરો.",
    startMastering: "નિપુણ બનો",
    features: ["60+ Excel ફંક્શન્સ", "Groq દ્વારા AI સહાયક", "વાસ્તવિક કાર્ય માટે ટ્યૂટોરિયલ"],
    dashboardLabel: "XLSBUDDY ડેશબોર્ડ", welcomeBack: "પાછા આવ્યા",
    dashHeroSub: "Excel ફૉર્મ્યુલા શોધો, ટ્યૂટોરિયલ શીખો, AI મદદ મેળવો.",
    browseFunctions: "ફંક્શન જુઓ", askAI: "AI પૂછો", tutorials: "ટ્યૂટોરિયલ",
    statFunctions: "ફંક્શન", statTutorials: "ટ્યૂટોરિયલ", statAssistant: "સહાયક", statSupport: "સહાય",
    toolsLabel: "સાધનો", toolsHeading: "જે જોઈએ તે બધું.",
    tileFnTitle: "ફંક્શન લાઇબ્રેરી", tileFnDesc: "60+ Excel ફંક્શન શ્રેણી પ્રમાણે જુઓ.",
    tileAiTitle: "AI સહાયક", tileAiDesc: "Excel વિશે ગમે તે પૂછો — તત્કાળ જવાબ મેળવો.",
    tileTutTitle: "ટ્યૂટોરિયલ", tileTutDesc: "પિવૉટ, લૂકઅપ, કન્ડિશનલ ફૉર્મેટ માટે ગાઇડ.",
    tileBmTitle: "બુકમાર્ક", tileBmDesc: "સેવ કરેલ ફંક્શન ઝડપથી ઍક્સેસ કરો.",
    tileFgTitle: "ફૉર્મ્યુલા જનરેટર", tileFgDesc: "સરળ ભાષામાં કહો — Excel ફૉર્મ્યુલા મળશે.",
    tileQsTitle: "ઝડપી શોધ", tileQsDesc: "એક સેકન્ડમાં ફંક્શન શોધો.",
    proTipLabel: "Pro ટિપ", proTipTitle: "અમર્યાદિત AI ચૅટ + અદ્યતન ટ્યૂટોરિયલ",
    proTipDesc: "XLSBuddy Pro માં અપગ્રેડ કરો અને અમર્યાદિત મદદ મેળવો.",
    upgradeToPro: "Pro માં અપગ્રેડ", shareApp: "ઍપ શેર કરો",
  },
  kn: {
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", learn: "ಕಲಿಯಿರಿ", functions: "ಕಾರ್ಯಗಳು",
    aiChat: "AI ಚಾಟ್", formulaAI: "ಫಾರ್ಮುಲಾ AI", excelAI: "Excel AI",
    pricing: "ಬೆಲೆ", signIn: "ಸೈನ್ ಇನ್", signOut: "ಸೈನ್ ಔಟ್",
    upgrade: "ಅಪ್‌ಗ್ರೇಡ್", getStarted: "ಪ್ರಾರಂಭಿಸಿ", bookmarks: "ಬುಕ್‌ಮಾರ್ಕ್‌ಗಳು",
    reviews: "ವಿಮರ್ಶೆಗಳು", admin: "ಆಡ್ಮಿನ್", aiRespondingIn: "AI ಉತ್ತರಿಸುತ್ತದೆ",
    signedInAs: "ಲಾಗಿನ್:", free: "ಉಚಿತ", pro: "PRO",
    upgradeToProMenu: "Pro ಗೆ ಅಪ್‌ಗ್ರೇಡ್",
    pickUpTitle: "ನೀವು ನಿಲ್ಲಿಸಿದ ಕಡೆಯಿಂದ ಮುಂದುವರಿಸಿ.",
    pickUpSubtitle: "ನಿಮ್ಮ ಉಳಿಸಿದ ಚಾಟ್‌ಗಳು, ಇತ್ತೀಚಿನ ಹುಡುಕಾಟಗಳು ಮತ್ತು ಬುಕ್‌ಮಾರ್ಕ್ ಮಾಡಿದ ಟ್ಯುಟೋರಿಯಲ್‌ಗಳು ಕಾಯುತ್ತಿವೆ.",
    signInToAccount: "ನಿಮ್ಮ ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ.",
    emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    forgotPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?",
    newHere: "ಹೊಸಬರಾ?",
    createAccountLink: "ಖಾತೆ ತೆರೆಯಿರಿ",
    signingIn: "ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ…",
    createAccountTitle: "Excel ಕಲಿಯಿರಿ — ಉಚಿತವಾಗಿ.",
    createAccountOverline: "ಖಾತೆ ತೆರೆಯಿರಿ",
    namePlaceholder: "ನಿಮ್ಮ ಹೆಸರು",
    emailPlaceholder: "ನಿಮ್ಮ ಇಮೇಲ್",
    passwordPlaceholder: "ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳು",
    createAccountBtn: "ಖಾತೆ ತೆರೆಯಿರಿ",
    creating: "ರಚಿಸಲಾಗುತ್ತಿದೆ…",
    alreadyHaveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
    stopGooglingTitle: "Google ಮಾಡುವುದನ್ನು ನಿಲ್ಲಿಸಿ.",
    startMastering: "ಪ್ರಾವೀಣ್ಯ ಪಡೆಯಿರಿ",
    features: ["60+ Excel ಕಾರ್ಯಗಳು", "Groq ಮೂಲಕ AI ಸಹಾಯಕ", "ನೈಜ ಕೆಲಸಗಳಿಗಾಗಿ ಟ್ಯುಟೋರಿಯಲ್‌ಗಳು"],
    dashboardLabel: "XLSBUDDY ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", welcomeBack: "ಮರಳಿ ಸ್ವಾಗತ",
    dashHeroSub: "Excel ಸೂತ್ರಗಳನ್ನು ಹುಡುಕಿ, ಟ್ಯುಟೋರಿಯಲ್ ಕಲಿಯಿರಿ, AI ಸಹಾಯ ಪಡೆಯಿರಿ.",
    browseFunctions: "ಕಾರ್ಯಗಳನ್ನು ನೋಡಿ", askAI: "AI ಕೇಳಿ", tutorials: "ಟ್ಯುಟೋರಿಯಲ್‌ಗಳು",
    statFunctions: "ಕಾರ್ಯಗಳು", statTutorials: "ಟ್ಯುಟೋರಿಯಲ್", statAssistant: "ಸಹಾಯಕ", statSupport: "ಬೆಂಬಲ",
    toolsLabel: "ಸಾಧನಗಳು", toolsHeading: "ನಿಮಗೆ ಬೇಕಾದ ಎಲ್ಲವೂ.",
    tileFnTitle: "ಕಾರ್ಯ ಗ್ರಂಥಾಲಯ", tileFnDesc: "60+ Excel ಕಾರ್ಯಗಳನ್ನು ವರ್ಗದ ಮೂಲಕ ನೋಡಿ.",
    tileAiTitle: "AI ಸಹಾಯಕ", tileAiDesc: "Excel ಬಗ್ಗೆ ಏನಾದರೂ ಕೇಳಿ — ತಕ್ಷಣ ಉತ್ತರ ಪಡೆಯಿರಿ.",
    tileTutTitle: "ಟ್ಯುಟೋರಿಯಲ್", tileTutDesc: "ಪಿವೋಟ್, ಲುಕ್‌ಅಪ್, ಷರತ್ತು ಸ್ವರೂಪದ ಗೈಡ್‌ಗಳು.",
    tileBmTitle: "ಬುಕ್‌ಮಾರ್ಕ್", tileBmDesc: "ಉಳಿಸಿದ ಕಾರ್ಯಗಳು ಮತ್ತು ಟ್ಯುಟೋರಿಯಲ್‌ಗಳನ್ನು ತ್ವರಿತವಾಗಿ ಪ್ರವೇಶಿಸಿ.",
    tileFgTitle: "ಫಾರ್ಮುಲಾ ಜನರೇಟರ್", tileFgDesc: "ಸರಳ ಭಾಷೆಯಲ್ಲಿ ಹೇಳಿ — Excel ಸೂತ್ರ ಪಡೆಯಿರಿ.",
    tileQsTitle: "ತ್ವರಿತ ಹುಡುಕಾಟ", tileQsDesc: "ಯಾವುದೇ ಕಾರ್ಯವನ್ನು ಒಂದು ಸೆಕೆಂಡಿನಲ್ಲಿ ಹುಡುಕಿ.",
    proTipLabel: "Pro ಸಲಹೆ", proTipTitle: "ಅಪರಿಮಿತ AI ಚಾಟ್ + ಮುಂದುವರಿದ ಟ್ಯುಟೋರಿಯಲ್",
    proTipDesc: "XLSBuddy Pro ಗೆ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ ಅಪರಿಮಿತ ಸಹಾಯ ಪಡೆಯಿರಿ.",
    upgradeToPro: "Pro ಗೆ ಅಪ್‌ಗ್ರೇಡ್", shareApp: "ಅಪ್ಲಿಕೇಶನ್ ಹಂಚಿ",
  },
  ml: {
    dashboard: "ഡാഷ്‌ബോർഡ്", learn: "പഠിക്കൂ", functions: "ഫങ്ഷനുകൾ",
    aiChat: "AI ചാറ്റ്", formulaAI: "ഫോർമുല AI", excelAI: "Excel AI",
    pricing: "വില", signIn: "സൈൻ ഇൻ", signOut: "സൈൻ ഔട്ട്",
    upgrade: "അപ്‌ഗ്രേഡ്", getStarted: "ആരംഭിക്കൂ", bookmarks: "ബുക്ക്‌മാർക്കുകൾ",
    reviews: "അവലോകനങ്ങൾ", admin: "അഡ്‌മിൻ", aiRespondingIn: "AI മറുപടി നൽകുന്നു",
    signedInAs: "ലോഗിൻ:", free: "സൗജന്യം", pro: "PRO",
    upgradeToProMenu: "Pro-ലേക്ക് അപ്‌ഗ്രേഡ്",
    pickUpTitle: "നിർത്തിയ ഇടത്ത് നിന്ന് തുടരൂ.",
    pickUpSubtitle: "നിങ്ങളുടെ സേവ് ചെയ്ത ചാറ്റുകൾ, സമീപകാല തിരയലുകൾ, ബുക്ക്‌മാർക്ക് ചെയ്ത ട്യൂട്ടോറിയലുകൾ കാത്തിരിക്കുന്നു.",
    signInToAccount: "നിങ്ങളുടെ അക്കൗണ്ടിൽ സൈൻ ഇൻ ചെയ്യൂ.",
    emailAddress: "ഇമെയിൽ വിലാസം",
    password: "പാസ്‌വേഡ്",
    forgotPassword: "പാസ്‌വേഡ് മറന്നോ?",
    newHere: "പുതിയ ഉപയോക്താവോ?",
    createAccountLink: "അക്കൗണ്ട് ഉണ്ടാക്കൂ",
    signingIn: "സൈൻ ഇൻ ആകുന്നു…",
    createAccountTitle: "Excel പഠിക്കൂ — സൗജന്യമായി.",
    createAccountOverline: "അക്കൗണ്ട് ഉണ്ടാക്കൂ",
    namePlaceholder: "നിങ്ങളുടെ പേര്",
    emailPlaceholder: "നിങ്ങളുടെ ഇമെയിൽ",
    passwordPlaceholder: "കുറഞ്ഞത് 6 അക്ഷരങ്ങൾ",
    createAccountBtn: "അക്കൗണ്ട് ഉണ്ടാക്കൂ",
    creating: "ഉണ്ടാക്കുന്നു…",
    alreadyHaveAccount: "ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?",
    stopGooglingTitle: "Google ചെയ്യുന്നത് നിർത്തൂ.",
    startMastering: "വൈദഗ്ദ്ധ്യം നേടൂ",
    features: ["60+ Excel ഫങ്ഷനുകൾ", "Groq ഉപയോഗിച്ച് AI അസിസ്റ്റന്റ്", "യഥാർഥ ജോലിക്കായി ട്യൂട്ടോറിയലുകൾ"],
    dashboardLabel: "XLSBUDDY ഡാഷ്‌ബോർഡ്", welcomeBack: "തിരികെ സ്വാഗതം",
    dashHeroSub: "Excel ഫോർമുലകൾ തിരയൂ, ട്യൂട്ടോറിയലുകൾ പഠിക്കൂ, AI സഹായം നേടൂ.",
    browseFunctions: "ഫംഗ്‌ഷനുകൾ കാണൂ", askAI: "AI ചോദിക്കൂ", tutorials: "ട്യൂട്ടോറിയലുകൾ",
    statFunctions: "ഫംഗ്‌ഷനുകൾ", statTutorials: "ട്യൂട്ടോറിയൽ", statAssistant: "സഹായകൻ", statSupport: "സഹായം",
    toolsLabel: "ടൂളുകൾ", toolsHeading: "നിങ്ങൾക്ക് ആവശ്യമുള്ളതെല്ലാം.",
    tileFnTitle: "ഫംഗ്‌ഷൻ ലൈബ്രറി", tileFnDesc: "60+ Excel ഫംഗ്‌ഷനുകൾ വർഗ്ഗം തിരിച്ച് കാണൂ.",
    tileAiTitle: "AI സഹായകൻ", tileAiDesc: "Excel-നെ കുറിച്ച് എന്തും ചോദിക്കൂ — ഉടൻ ഉത്തരം നേടൂ.",
    tileTutTitle: "ട്യൂട്ടോറിയലുകൾ", tileTutDesc: "പിവറ്റ്, ലുക്കപ്പ്, ഷർത്ത് ഫോർമാറ്റ് ഗൈഡുകൾ.",
    tileBmTitle: "ബുക്ക്‌മാർക്കുകൾ", tileBmDesc: "സേവ് ചെയ്ത ഫംഗ്‌ഷനുകളും ട്യൂട്ടോറിയലുകളും വേഗം ആക്‌സസ് ചെയ്യൂ.",
    tileFgTitle: "ഫോർമുല ജനറേറ്റർ", tileFgDesc: "ലളിതമായി പറയൂ — Excel ഫോർമുല ലഭിക്കും.",
    tileQsTitle: "വേഗ തിരയൽ", tileQsDesc: "ഒരു സെക്കൻഡിൽ ഏതു ഫംഗ്‌ഷനും കണ്ടെത്തൂ.",
    proTipLabel: "Pro നുറുങ്ങ്", proTipTitle: "അൺലിമിറ്റഡ് AI ചാറ്റ് + ഉന്നത ട്യൂട്ടോറിയൽ",
    proTipDesc: "XLSBuddy Pro-ലേക്ക് അപ്‌ഗ്രേഡ് ചെയ്ത് അൺലിമിറ്റഡ് സഹായം നേടൂ.",
    upgradeToPro: "Pro-ലേക്ക് അപ്‌ഗ്രേഡ്", shareApp: "ആപ്പ് പങ്കിടൂ",
  },
  bn: {
    dashboard: "ড্যাশবোর্ড", learn: "শিখুন", functions: "ফাংশন",
    aiChat: "AI চ্যাট", formulaAI: "ফর্মুলা AI", excelAI: "Excel AI",
    pricing: "মূল্য", signIn: "সাইন ইন", signOut: "সাইন আউট",
    upgrade: "আপগ্রেড", getStarted: "শুরু করুন", bookmarks: "বুকমার্ক",
    reviews: "পর্যালোচনা", admin: "অ্যাডমিন", aiRespondingIn: "AI উত্তর দেয়",
    signedInAs: "লগইন:", free: "বিনামূল্যে", pro: "PRO",
    upgradeToProMenu: "Pro-তে আপগ্রেড করুন",
    pickUpTitle: "যেখানে ছেড়েছিলেন সেখান থেকে শুরু করুন।",
    pickUpSubtitle: "আপনার সেভ করা চ্যাট, সাম্প্রতিক অনুসন্ধান এবং বুকমার্ক করা টিউটোরিয়াল অপেক্ষা করছে।",
    signInToAccount: "আপনার অ্যাকাউন্টে সাইন ইন করুন।",
    emailAddress: "ইমেইল ঠিকানা",
    password: "পাসওয়ার্ড",
    forgotPassword: "পাসওয়ার্ড ভুলে গেছেন?",
    newHere: "নতুন এখানে?",
    createAccountLink: "অ্যাকাউন্ট তৈরি করুন",
    signingIn: "সাইন ইন হচ্ছে…",
    createAccountTitle: "Excel শিখুন — বিনামূল্যে।",
    createAccountOverline: "অ্যাকাউন্ট তৈরি করুন",
    namePlaceholder: "আপনার নাম",
    emailPlaceholder: "আপনার ইমেইল",
    passwordPlaceholder: "কমপক্ষে ৬ অক্ষর",
    createAccountBtn: "অ্যাকাউন্ট তৈরি করুন",
    creating: "তৈরি হচ্ছে…",
    alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    stopGooglingTitle: "Google করা বন্ধ করুন।",
    startMastering: "দক্ষতা অর্জন করুন",
    features: ["60+ Excel ফাংশন", "Groq দ্বারা AI সহায়তা", "বাস্তব কাজের জন্য টিউটোরিয়াল"],
    dashboardLabel: "XLSBUDDY ড্যাশবোর্ড", welcomeBack: "ফিরে আসুন",
    dashHeroSub: "Excel ফর্মুলা খুঁজুন, টিউটোরিয়াল শিখুন, AI সাহায্য পান।",
    browseFunctions: "ফাংশন দেখুন", askAI: "AI জিজ্ঞেস করুন", tutorials: "টিউটোরিয়াল",
    statFunctions: "ফাংশন", statTutorials: "টিউটোরিয়াল", statAssistant: "সহকারী", statSupport: "সহায়তা",
    toolsLabel: "টুলস", toolsHeading: "আপনার যা দরকার সব।",
    tileFnTitle: "ফাংশন লাইব্রেরি", tileFnDesc: "60+ Excel ফাংশন বিভাগ অনুযায়ী দেখুন।",
    tileAiTitle: "AI সহকারী", tileAiDesc: "Excel সম্পর্কে যেকোনো প্রশ্ন করুন — তাৎক্ষণিক উত্তর পান।",
    tileTutTitle: "টিউটোরিয়াল", tileTutDesc: "পিভোট, লুকআপ, কন্ডিশনাল ফর্ম্যাটিং গাইড।",
    tileBmTitle: "বুকমার্ক", tileBmDesc: "সংরক্ষিত ফাংশন এবং টিউটোরিয়ালে দ্রুত প্রবেশ।",
    tileFgTitle: "ফর্মুলা জেনারেটর", tileFgDesc: "সহজ ভাষায় বলুন — সঠিক Excel ফর্মুলা পান।",
    tileQsTitle: "দ্রুত অনুসন্ধান", tileQsDesc: "যেকোনো ফাংশন এক সেকেন্ডে খুঁজুন।",
    proTipLabel: "Pro টিপ", proTipTitle: "সীমাহীন AI চ্যাট + উন্নত টিউটোরিয়াল",
    proTipDesc: "XLSBuddy Pro-তে আপগ্রেড করুন এবং সীমাহীন সাহায্য পান।",
    upgradeToPro: "Pro-তে আপগ্রেড", shareApp: "অ্যাপ শেয়ার করুন",
  },
  pa: {
    dashboard: "ਡੈਸ਼ਬੋਰਡ", learn: "ਸਿੱਖੋ", functions: "ਫੰਕਸ਼ਨ",
    aiChat: "AI ਚੈਟ", formulaAI: "ਫਾਰਮੂਲਾ AI", excelAI: "Excel AI",
    pricing: "ਕੀਮਤ", signIn: "ਸਾਈਨ ਇਨ", signOut: "ਸਾਈਨ ਆਊਟ",
    upgrade: "ਅੱਪਗ੍ਰੇਡ", getStarted: "ਸ਼ੁਰੂ ਕਰੋ", bookmarks: "ਬੁੱਕਮਾਰਕ",
    reviews: "ਸਮੀਖਿਆਵਾਂ", admin: "ਐਡਮਿਨ", aiRespondingIn: "AI ਜਵਾਬ ਦਿੰਦਾ ਹੈ",
    signedInAs: "ਲੌਗਇਨ:", free: "ਮੁਫ਼ਤ", pro: "PRO",
    upgradeToProMenu: "Pro ਵਿੱਚ ਅੱਪਗ੍ਰੇਡ ਕਰੋ",
    pickUpTitle: "ਜਿੱਥੇ ਛੱਡਿਆ ਸੀ ਉੱਥੋਂ ਸ਼ੁਰੂ ਕਰੋ।",
    pickUpSubtitle: "ਤੁਹਾਡੀਆਂ ਸੇਵ ਕੀਤੀਆਂ ਚੈਟਾਂ, ਹਾਲੀਆ ਖੋਜਾਂ ਅਤੇ ਬੁੱਕਮਾਰਕ ਕੀਤੇ ਟਿਊਟੋਰੀਅਲ ਉਡੀਕ ਕਰ ਰਹੇ ਹਨ।",
    signInToAccount: "ਆਪਣੇ ਖਾਤੇ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ।",
    emailAddress: "ਈਮੇਲ ਪਤਾ",
    password: "ਪਾਸਵਰਡ",
    forgotPassword: "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?",
    newHere: "ਨਵੇਂ ਹੋ?",
    createAccountLink: "ਖਾਤਾ ਬਣਾਓ",
    signingIn: "ਸਾਈਨ ਇਨ ਹੋ ਰਿਹਾ ਹੈ…",
    createAccountTitle: "Excel ਸਿੱਖੋ — ਮੁਫ਼ਤ ਵਿੱਚ।",
    createAccountOverline: "ਖਾਤਾ ਬਣਾਓ",
    namePlaceholder: "ਤੁਹਾਡਾ ਨਾਮ",
    emailPlaceholder: "ਤੁਹਾਡੀ ਈਮੇਲ",
    passwordPlaceholder: "ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰ",
    createAccountBtn: "ਖਾਤਾ ਬਣਾਓ",
    creating: "ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ…",
    alreadyHaveAccount: "ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?",
    stopGooglingTitle: "Google ਕਰਨਾ ਬੰਦ ਕਰੋ।",
    startMastering: "ਮੁਹਾਰਤ ਹਾਸਲ ਕਰੋ",
    features: ["60+ Excel ਫੰਕਸ਼ਨ", "Groq ਦੁਆਰਾ AI ਸਹਾਇਕ", "ਅਸਲ ਕੰਮਾਂ ਲਈ ਟਿਊਟੋਰੀਅਲ"],
    dashboardLabel: "XLSBUDDY ਡੈਸ਼ਬੋਰਡ", welcomeBack: "ਵਾਪਸ ਜੀ ਆਇਆਂ ਨੂੰ",
    dashHeroSub: "Excel ਫਾਰਮੂਲੇ ਲੱਭੋ, ਟਿਊਟੋਰੀਅਲ ਸਿੱਖੋ, AI ਮਦਦ ਲਓ।",
    browseFunctions: "ਫੰਕਸ਼ਨ ਵੇਖੋ", askAI: "AI ਪੁੱਛੋ", tutorials: "ਟਿਊਟੋਰੀਅਲ",
    statFunctions: "ਫੰਕਸ਼ਨ", statTutorials: "ਟਿਊਟੋਰੀਅਲ", statAssistant: "ਸਹਾਇਕ", statSupport: "ਸਹਾਇਤਾ",
    toolsLabel: "ਟੂਲਸ", toolsHeading: "ਜੋ ਚਾਹੀਦਾ ਹੈ ਸਭ ਕੁਝ।",
    tileFnTitle: "ਫੰਕਸ਼ਨ ਲਾਇਬ੍ਰੇਰੀ", tileFnDesc: "60+ Excel ਫੰਕਸ਼ਨ ਸ਼੍ਰੇਣੀ ਅਨੁਸਾਰ ਵੇਖੋ।",
    tileAiTitle: "AI ਸਹਾਇਕ", tileAiDesc: "Excel ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ — ਤੁਰੰਤ ਜਵਾਬ ਲਓ।",
    tileTutTitle: "ਟਿਊਟੋਰੀਅਲ", tileTutDesc: "ਪਿਵੋਟ, ਲੁੱਕਅਪ, ਕੰਡੀਸ਼ਨਲ ਫਾਰਮੈਟਿੰਗ ਗਾਈਡ।",
    tileBmTitle: "ਬੁੱਕਮਾਰਕ", tileBmDesc: "ਸੇਵ ਕੀਤੇ ਫੰਕਸ਼ਨਾਂ ਅਤੇ ਟਿਊਟੋਰੀਅਲਾਂ ਤੱਕ ਤੇਜ਼ ਪਹੁੰਚ।",
    tileFgTitle: "ਫਾਰਮੂਲਾ ਜਨਰੇਟਰ", tileFgDesc: "ਸਧਾਰਨ ਭਾਸ਼ਾ ਵਿੱਚ ਦੱਸੋ — Excel ਫਾਰਮੂਲਾ ਮਿਲੇਗਾ।",
    tileQsTitle: "ਤੇਜ਼ ਖੋਜ", tileQsDesc: "ਕੋਈ ਵੀ ਫੰਕਸ਼ਨ ਇੱਕ ਸਕਿੰਟ ਵਿੱਚ ਲੱਭੋ।",
    proTipLabel: "Pro ਟਿਪ", proTipTitle: "ਅਸੀਮਿਤ AI ਚੈਟ + ਉੱਨਤ ਟਿਊਟੋਰੀਅਲ",
    proTipDesc: "XLSBuddy Pro ਵਿੱਚ ਅੱਪਗ੍ਰੇਡ ਕਰੋ ਅਤੇ ਅਸੀਮਿਤ ਮਦਦ ਪਾਓ।",
    upgradeToPro: "Pro ਵਿੱਚ ਅੱਪਗ੍ਰੇਡ", shareApp: "ਐਪ ਸ਼ੇਅਰ ਕਰੋ",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(
    () => localStorage.getItem("xlsbuddy_lang") || "en"
  );

  const setLanguage = (code) => {
    localStorage.setItem("xlsbuddy_lang", code);
    setLanguageState(code);
  };

  const current = LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];
  const t = (key) => T[language]?.[key] ?? T.en[key] ?? key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, current, LANGUAGES, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
